theme = "material_deep_ocean"

[editor]
line-number = "relative"
mouse = true


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"  # Other options: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.whitespace.render]
all = true

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name"]
right = ["diagnostics", "position"]

[editor.gutters]
layout = ["line-numbers", "diagnostics", "diff"]   

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'

[editor.lsp]
display-inlay-hints = true   

[keys.normal]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]




